name: "Report Tachometer Results"
description: "Report the results of Polymer/tachometer in a comment for PRs"
author: andrewiggins
branding:
  icon: bar-chart-2 # clipboard, file-text, flag, trending-up, upload
  color: purple
inputs:
  github_token:
    description: "The GITHUB_TOKEN for the current workflow run"
    required: false
    default: ${{github.token}}
  path:
    description: "The path to the results JSON file of running tachometer"
    required: true
  use-check:
    description: "Report status as a CI Check instead of using a comment [experimental]"
    required: false
    default: "false"
runs:
  using: "node12"
  main: "dist/action.js"
