name: Main

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm test
      - name: Report Tachometer Result
        uses: ./
        with:
          path: results.json
