name: PR Multi Init Flow

on:
  pull_request:
    branches:
      - "**"

# Demo how to use the multi init flow
#
# In this flow, a workflow must specify which tachometer-reporter-action will
# initialize the comment by setting initialize to true for one action and
# initialize to false for all other actions.

jobs:
  bench_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Could use this to simulate benchmark running for random number of seconds
          echo $((($RANDOM%(5000-1000))+1000))
      - name: Report Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@master
        with:
          path: tests/results/test-results.json
          initialize: true # Should work without report-id
          pr-bench-name: local-framework
          base-bench-name: base-framework

  bench_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Report Other Tachometer Result
        uses: andrewiggins/tachometer-reporter-action@master
        with:
          path: tests/results/other-results.json
          initialize: false
