name: Pull Request Test

on:
  pull_request:
    branches:
      - "**"

jobs:
  pr_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm test
      - name: Report Tachometer Result
        uses: ./
        with:
          path: tests/results/test-results.json
          local-version: local-framework
          base-version: base-framework
      # - name: Report Other Tachometer Result
      #   uses: ./
      #   with:
      #     path: tests/results/other-results.json
